spring.datasource.url=jdbc:mysql://localhost:3306/musicdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.thymeleaf.cache=false
spring.resources.cache-period=0

jwt.secret=a2V5c3VwZXJzZWNyZXRmb3Jqd3RhdXRoZW50aWNhdGlvbnN5c3RlbTEyMzQ1Njc4OTBhYmNkZWZnaGlqa2xtbm9wcXJz
jwt.expiration=86400000
youtube.api.key=AIzaSyDVAU-86Uh6HLCESrlb6wGGTw52oOUtzM8
genius.api.token=PsD8cSQbuS-_sNFuIqVUVJZulx8VRgPUyUUeJveD9rfLqaveLWhh-BPuFlwAMccT